### ISSUE TITLE
Problems found loading plugins: The Symfony Support 

### ISSUE THREAD

**Issue by andrii-pez** [shyim/qodana-php#1]
Hi, I tries your custom image for Qodana and had some problems with it while running 
```
2022-05-27 12:58:23,339 [   1363] SEVERE - #c.i.i.p.PluginManager - Problems found loading plugins:
  The Symfony Support (id=fr.adrienbrault.idea.symfony2plugin, path=/opt/idea/plugins/SymfonyPlugin) plugin Plugin 'Symfony Support' requires plugin 'com.jetbrains.twig' to be installed
java.lang.Throwable: Problems found loading plugins:
  The Symfony Support (id=fr.adrienbrault.idea.symfony2plugin, path=/opt/idea/plugins/SymfonyPlugin) plugin Plugin 'Symfony Support' requires plugin 'com.jetbrains.twig' to be installed
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.ide.plugins.PluginManagerCore.preparePluginErrors(PluginManagerCore.java:543)
	at com.intellij.ide.plugins.PluginManagerCore.initializePlugins(PluginManagerCore.java:854)
	at com.intellij.ide.plugins.PluginManagerCore.loadAndInitializePlugins(PluginManagerCore.java:987)
	at com.intellij.ide.plugins.PluginManagerCore.lambda$getOrScheduleLoading$5(PluginManagerCore.java:622)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:2984)
	at com.intellij.idea.StartupUtil.start(StartupUtil.java:270)
	at com.intellij.idea.Main.bootstrap(Main.java:118)
	at com.intellij.idea.Main.main(Main.java:79)
2022-05-27 12:58:23,350 [   1374] SEVERE - #c.i.i.p.PluginManager - PhpStorm 2022.1 EAP  Build #QDPHP-221.5728.72
2022-05-27 12:58:23,365 [   1389] SEVERE - #c.i.i.p.PluginManager - JDK: 11.0.12; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-05-27 12:58:23,367 [   1391] SEVERE - #c.i.i.p.PluginManager - OS: Linux
...
```

It seems `Twig` plugin is required. 

P.S. By the way - thanks for customized image, it's a great idea

**Comment by shyim** [comment]
AHH that could be the reason why I have so many errors :D

**Comment by shyim** [comment]
Lets see if this helps https://github.com/shyim/qodana-php/commit/1b4403fa8402bcffacf20e2916bb1f03ce780628

**Comment by andrii-pez** [comment]
Yep, it helped - now works correct. 
Thanks you!
